--DROP_SCHEMA
--CREATE_INDEX
--CREATE_TABLE
--ALTER_TABLE
--DROP TABLE 

DROP SCHEMA Archive_TBD
GO

CREATE NONCLUSTERED INDEX NCI_companyid ON dbo.companytx
(
	companyid ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
go

CREATE TABLE dbo.CCardTx
(
	CCardTxID INT NOT NULL,
	CCardTxOther VARCHAR(8) NULL,
	CONSTRAINT CCardTxID PRIMARY KEY CLUSTERED ( CCardTxID ASC ) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE dbo.CompanyTx CHECK CONSTRAINT FK_ClientTx_BOATx
GO

ALTER TABLE dbo.CompanyTx  WITH NOCHECK ADD  CONSTRAINT FK_ClientTx_CCardTx FOREIGN KEY(CCardTxID)
REFERENCES dbo.CCardTx (CCardTxID)
NOT FOR REPLICATION
GO